# -*- coding: utf-8 -*-
"""In_classs_activity 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp7F4rJ9tNW1BPaA4FcNabOiJWbGLdp7

##Instructions for In Class Activity 1

You must find all errors in your scripts. But because you are communicating with a machine, not a person, you have to be exact: the computer cannot understand you at all if there are errors, bugs, in your code. Or the computer may do exactly what you wrote, but not what you meant to do.

Add a comment to the file that describes what you did.

Change the file name to "your name In Class Activity 1" and hand in these corrected Python scripts!

Question 1
"""

x = 15
y = 5
z = 3
k = x / y
print(k)   #removed "y=0" since any number divided by zero iss undefined and causes an error

"""Question 2"""

x = 10
y = 20
z = 30
print(x, y, z)    #removed the indent in line 4

"""Question 3"""

# This program converts miles to km

miles = 10
multiplier = 1.609344
km = miles * multiplier   #added the letter "i" to "multplier" to match the variable
print(km)

"""Question 4"""

x = 1
y = 10
z = 2
t = 15
print((x * t) / (y / z))   #added a closed parenthesis at the end
print('Done')

"""Question 5"""

fruit = "kiwi"
print(fruit, fruit, fruit)  #added the letter "i" to "frut" to match the variable