# -*- coding: utf-8 -*-
"""in_classs_activity_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARFzPFjC7h4qXRSS3MpXW0EHSO68jEK1

**Question 1:**
"""

base = 10
height = 4
area = (base * height) // 2
print(area,'cm')

"""**Question 2:**"""

fenceLength = 15
gardenLength = 50
gardenWidth = 80
gardenPerimeter = 2 * (gardenLength + gardenWidth)
fenceNeeded = ((gardenPerimeter / fenceLength) + 1)
print(int(fenceNeeded),'fences are needed')

"""**Question 3:**"""

totalAmount = 835
print ('Total Amount:',totalAmount,'cents')
dollars =  (totalAmount // 100)
print ('Dollars:',dollars)
quarters = (totalAmount % 100) // 25
print ('Quarters:',quarters)
dimes = (totalAmount % 25) // 10
print ('Dimes:',dimes)

"""**Question 4:**"""

print ('One')
print (' Two')
print ('  Three')  #didn't know how to do this with escape character

"""**Question 5:**"""

name = input()
print ('\"'+ name + '\"','is a common name.')

"""**Question 6:**"""

filePath = ('C:\\'+"Users"+'\\'+"Documents"+'\\'+"MyFile.txt")
print (filePath)