# -*- coding: utf-8 -*-
"""In_Class_Activity_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymQx1zaxGYfRHIzgMzInfE7w-6GHQVmP
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
initializeTurtle()
import ColabTurtle.Turtle as turtle

"""**Question 1:**"""

#Without the for loop:

turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)
turtle.left(45)
turtle.forward(50)

initializeTurtle()

#With the for loop:

for i in range(8):
  turtle.left(45)
  turtle.forward(50)

"""**Question 2:**"""

#Without the for loop:

turtle.color("red")
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)

turtle.penup()
turtle.goto(200,200)
turtle.pendown()
turtle.color("green")
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)

initializeTurtle()

#With the for loop:
turtle.color("red")
for i in range(5):
  turtle.forward(100)
  turtle.left(144)

turtle.penup()
turtle.goto(200,200)
turtle.pendown()
turtle.color("green")

for i in range(5):
  turtle.forward(100)
  turtle.left(144)

initializeTurtle()

"""**Question 3:**"""

initializeTurtle()
#roof
turtle.color("red")
turtle.right(90)
turtle.forward(100)
turtle.left(120)
turtle.forward(150)
turtle.left(120)
turtle.forward(150)
turtle.left(120)
turtle.forward(100)
#house
turtle.forward(50)
turtle.color("yellow")
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(150)

#door
turtle.penup()
turtle.goto(450,400)
turtle.pendown()
turtle.color("green")
turtle.forward(90)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(50)